# Generated by Django 4.0.1 on 2022-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='href',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
