# Generated by Django 4.0.1 on 2022-05-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_operations_quality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operations',
            new_name='new_Operations',
        ),
    ]
